export const Skills: { [key: string]: string[] } = {
  Backend: [
    "Nodejs",
    "Express.js",
    "ROR",
    "Python",
    "GraphQL",
    "RuboCop",
    "RSpec",
    "lefthook",
    "Redis",
    "Sidekiq",
    "Heroku",
    "AWS",
    "Lambda",
    "MongoDB",
    "Dynamodb",
  ],
  Frontend: [
    "React.Js",
    "Next.Js",
    "Vue.js",
    "Stimulus.js",
    "Reflex",
    "Hotwire-Turbo",
    "Bootstrap",
    "Tailwind",
    "UIKIT",
  ],
  Others: [
    "Stripe",
    "Twilio",
    "SendGrid",
    "Postmark",
    "Pusher",
    "Auth0",
    "Google Maps",
    "GPT-3",
    "GPT-4",
    "Agile",
    "Scrum",
    "Jira",
    "CircleCI",
  ],
};
